// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DemoLib {
    
    
    public partial class ScreenResolution {
        
        private Gtk.VBox vbox;
        
        private Gtk.Image image;
        
        private Gtk.HBox hbox;
        
        private Gtk.Frame frame_resolution;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table_resolution;
        
        private Gtk.CheckButton checkbox_fullscreen;
        
        private Gtk.RadioButton radio_1024x768;
        
        private Gtk.RadioButton radio_1280x1024;
        
        private Gtk.RadioButton radio_1400x1280;
        
        private Gtk.RadioButton radio_320x240;
        
        private Gtk.RadioButton radio_640x480;
        
        private Gtk.RadioButton radio_800x600;
        
        private Gtk.Label label_resolution;
        
        private Gtk.Frame frame_colour_quality;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.Table table_colour_quality;
        
        private Gtk.RadioButton radio_16bit;
        
        private Gtk.RadioButton radio_32bit;
        
        private Gtk.Label label_colours;
        
        private Gtk.Button button_play;
        
        private Gtk.Button button_exit;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget DemoLib.ScreenResolution
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "DemoLib.ScreenResolution";
            this.Title = Mono.Unix.Catalog.GetString("Settings");
            this.Icon = Gtk.IconTheme.Default.LoadIcon("stock_3d-colors", 16, 0);
            // Internal child DemoLib.ScreenResolution.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.vbox = new Gtk.VBox();
            this.vbox.Name = "vbox";
            // Container child vbox.Gtk.Box+BoxChild
            this.image = new Gtk.Image();
            this.image.Name = "image";
            this.image.Pixbuf = Gtk.IconTheme.Default.LoadIcon("stock_3d-colors", 48, 0);
            this.vbox.Add(this.image);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox[this.image]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox.Gtk.Box+BoxChild
            this.hbox = new Gtk.HBox();
            this.hbox.Name = "hbox";
            // Container child hbox.Gtk.Box+BoxChild
            this.frame_resolution = new Gtk.Frame();
            this.frame_resolution.Name = "frame_resolution";
            this.frame_resolution.LabelXalign = 0F;
            this.frame_resolution.BorderWidth = ((uint)(6));
            // Container child frame_resolution.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table_resolution = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
            this.table_resolution.Name = "table_resolution";
            this.table_resolution.RowSpacing = ((uint)(6));
            this.table_resolution.ColumnSpacing = ((uint)(6));
            this.table_resolution.BorderWidth = ((uint)(6));
            // Container child table_resolution.Gtk.Table+TableChild
            this.checkbox_fullscreen = new Gtk.CheckButton();
            this.checkbox_fullscreen.CanFocus = true;
            this.checkbox_fullscreen.Name = "checkbox_fullscreen";
            this.checkbox_fullscreen.Label = Mono.Unix.Catalog.GetString("Fullscreen");
            this.checkbox_fullscreen.DrawIndicator = true;
            this.checkbox_fullscreen.UseUnderline = true;
            this.table_resolution.Add(this.checkbox_fullscreen);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table_resolution[this.checkbox_fullscreen]));
            w3.TopAttach = ((uint)(3));
            w3.BottomAttach = ((uint)(4));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table_resolution.Gtk.Table+TableChild
            this.radio_1024x768 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("1024 x 768"));
            this.radio_1024x768.CanFocus = true;
            this.radio_1024x768.Name = "radio_1024x768";
            this.radio_1024x768.Active = true;
            this.radio_1024x768.DrawIndicator = true;
            this.radio_1024x768.UseUnderline = true;
            this.radio_1024x768.Group = new GLib.SList(System.IntPtr.Zero);
            this.table_resolution.Add(this.radio_1024x768);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table_resolution[this.radio_1024x768]));
            w4.LeftAttach = ((uint)(1));
            w4.RightAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table_resolution.Gtk.Table+TableChild
            this.radio_1280x1024 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("1280 x 1024"));
            this.radio_1280x1024.CanFocus = true;
            this.radio_1280x1024.Name = "radio_1280x1024";
            this.radio_1280x1024.DrawIndicator = true;
            this.radio_1280x1024.UseUnderline = true;
            this.radio_1280x1024.Group = this.radio_1024x768.Group;
            this.table_resolution.Add(this.radio_1280x1024);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table_resolution[this.radio_1280x1024]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table_resolution.Gtk.Table+TableChild
            this.radio_1400x1280 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("1400 x 1280"));
            this.radio_1400x1280.CanFocus = true;
            this.radio_1400x1280.Name = "radio_1400x1280";
            this.radio_1400x1280.DrawIndicator = true;
            this.radio_1400x1280.UseUnderline = true;
            this.radio_1400x1280.Group = this.radio_1024x768.Group;
            this.table_resolution.Add(this.radio_1400x1280);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table_resolution[this.radio_1400x1280]));
            w6.TopAttach = ((uint)(2));
            w6.BottomAttach = ((uint)(3));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table_resolution.Gtk.Table+TableChild
            this.radio_320x240 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("320 x 240"));
            this.radio_320x240.CanFocus = true;
            this.radio_320x240.Name = "radio_320x240";
            this.radio_320x240.DrawIndicator = true;
            this.radio_320x240.UseUnderline = true;
            this.radio_320x240.Group = this.radio_1024x768.Group;
            this.table_resolution.Add(this.radio_320x240);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table_resolution[this.radio_320x240]));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table_resolution.Gtk.Table+TableChild
            this.radio_640x480 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("640 x 480"));
            this.radio_640x480.CanFocus = true;
            this.radio_640x480.Name = "radio_640x480";
            this.radio_640x480.DrawIndicator = true;
            this.radio_640x480.UseUnderline = true;
            this.radio_640x480.Group = this.radio_1024x768.Group;
            this.table_resolution.Add(this.radio_640x480);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table_resolution[this.radio_640x480]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table_resolution.Gtk.Table+TableChild
            this.radio_800x600 = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("800 x 600"));
            this.radio_800x600.CanFocus = true;
            this.radio_800x600.Name = "radio_800x600";
            this.radio_800x600.DrawIndicator = true;
            this.radio_800x600.UseUnderline = true;
            this.radio_800x600.Group = this.radio_1024x768.Group;
            this.table_resolution.Add(this.radio_800x600);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table_resolution[this.radio_800x600]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table_resolution);
            this.frame_resolution.Add(this.GtkAlignment1);
            this.label_resolution = new Gtk.Label();
            this.label_resolution.Name = "label_resolution";
            this.label_resolution.LabelProp = Mono.Unix.Catalog.GetString("<b>Screen Resolution</b>");
            this.label_resolution.UseMarkup = true;
            this.frame_resolution.LabelWidget = this.label_resolution;
            this.hbox.Add(this.frame_resolution);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox[this.frame_resolution]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            // Container child hbox.Gtk.Box+BoxChild
            this.frame_colour_quality = new Gtk.Frame();
            this.frame_colour_quality.Name = "frame_colour_quality";
            this.frame_colour_quality.LabelXalign = 0F;
            this.frame_colour_quality.BorderWidth = ((uint)(6));
            // Container child frame_colour_quality.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.table_colour_quality = new Gtk.Table(((uint)(2)), ((uint)(1)), false);
            this.table_colour_quality.Name = "table_colour_quality";
            this.table_colour_quality.RowSpacing = ((uint)(6));
            this.table_colour_quality.ColumnSpacing = ((uint)(6));
            this.table_colour_quality.BorderWidth = ((uint)(6));
            // Container child table_colour_quality.Gtk.Table+TableChild
            this.radio_16bit = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("16 bit"));
            this.radio_16bit.CanFocus = true;
            this.radio_16bit.Name = "radio_16bit";
            this.radio_16bit.Active = true;
            this.radio_16bit.DrawIndicator = true;
            this.radio_16bit.UseUnderline = true;
            this.radio_16bit.Group = new GLib.SList(System.IntPtr.Zero);
            this.table_colour_quality.Add(this.radio_16bit);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table_colour_quality[this.radio_16bit]));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table_colour_quality.Gtk.Table+TableChild
            this.radio_32bit = new Gtk.RadioButton(Mono.Unix.Catalog.GetString("32 bit"));
            this.radio_32bit.CanFocus = true;
            this.radio_32bit.Name = "radio_32bit";
            this.radio_32bit.DrawIndicator = true;
            this.radio_32bit.UseUnderline = true;
            this.radio_32bit.Group = this.radio_16bit.Group;
            this.table_colour_quality.Add(this.radio_32bit);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table_colour_quality[this.radio_32bit]));
            w14.TopAttach = ((uint)(1));
            w14.BottomAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment2.Add(this.table_colour_quality);
            this.frame_colour_quality.Add(this.GtkAlignment2);
            this.label_colours = new Gtk.Label();
            this.label_colours.Name = "label_colours";
            this.label_colours.LabelProp = Mono.Unix.Catalog.GetString("<b>Colour Quality</b>");
            this.label_colours.UseMarkup = true;
            this.frame_colour_quality.LabelWidget = this.label_colours;
            this.hbox.Add(this.frame_colour_quality);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox[this.frame_colour_quality]));
            w17.Position = 1;
            w17.Expand = false;
            w17.Fill = false;
            this.vbox.Add(this.hbox);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox[this.hbox]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            w1.Add(this.vbox);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(w1[this.vbox]));
            w19.Position = 0;
            w19.Expand = false;
            w19.Fill = false;
            // Internal child DemoLib.ScreenResolution.ActionArea
            Gtk.HButtonBox w20 = this.ActionArea;
            w20.Events = ((Gdk.EventMask)(256));
            w20.Name = "DemoLib.ScreenResolution_ActionArea";
            w20.Spacing = 6;
            w20.BorderWidth = ((uint)(5));
            w20.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child DemoLib.ScreenResolution_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button_play = new Gtk.Button();
            this.button_play.CanDefault = true;
            this.button_play.CanFocus = true;
            this.button_play.Name = "button_play";
            this.button_play.UseUnderline = true;
            this.button_play.Label = Mono.Unix.Catalog.GetString("_Play");
            this.AddActionWidget(this.button_play, -5);
            Gtk.ButtonBox.ButtonBoxChild w21 = ((Gtk.ButtonBox.ButtonBoxChild)(w20[this.button_play]));
            w21.Expand = false;
            w21.Fill = false;
            // Container child DemoLib.ScreenResolution_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button_exit = new Gtk.Button();
            this.button_exit.CanDefault = true;
            this.button_exit.CanFocus = true;
            this.button_exit.Name = "button_exit";
            this.button_exit.UseStock = true;
            this.button_exit.UseUnderline = true;
            this.button_exit.Label = "gtk-quit";
            this.AddActionWidget(this.button_exit, 0);
            Gtk.ButtonBox.ButtonBoxChild w22 = ((Gtk.ButtonBox.ButtonBoxChild)(w20[this.button_exit]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 375;
            this.DefaultHeight = 276;
            this.Show();
        }
    }
}
